name: flutter_chat_poc_with_socket
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  socket_io_client: ^2.0.3+1
  get: 4.6.6
  flutter: 
    sdk: flutter
  uuid: ^4.1.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

